### ISSUE TITLE
Whoops Error in Production

### ISSUE THREAD

**Issue by namankumar80510** [hparadiz/technexus#12]
![Screenshot 2024-04-30 123744](https://github.com/hparadiz/technexus/assets/72571211/34b0c8b8-718a-4634-8f06-0ea505ddaada)

**URL**: https://technex.us/2023/09/port_forwarding_a_database_through_a_vpn_with_docker_and_nginx/

**Comment by hparadiz** [comment]
I fixed it. Thanks!
